version: '3.7'

services:
  app:
    build: ./app
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/logs:/app/logs
    expose:
      - 5000
    environment:
      - FLASK_ENV=development

  nginx:
    container_name: %API_TITLE_nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app